name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Build linux-amd64
      run: go build -o bootable-linux-amd64 .

    - name: Build windows-amd64
      run: GOOS=windows GOARCH=amd64 go build -o bootable-windows-amd64.exe .

    - name: Upload compiled executables
      uses: actions/upload-artifact@v4
      with:
        name: bootable-executables
        path: |
          bootable-linux-amd64

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download compiled executables
        uses: actions/download-artifact@v4
        with:
          name: bootable-executables
          path: .

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: Release ${{ github.ref_name }}
          body: |
            ## Release Notes
            This release contains the `bootable` executable for Linux (amd64 architectures).
            Download the appropriate version for your operating system and architecture.
          draft: false
          prerelease: false

      - name: Upload Linux executable asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./bootable-linux-amd64
          asset_name: bootable-linux-amd64
          asset_content_type: application/octet-stream
